# Generated by packaging/homebrew/formula.sh for tracebridge 0.1.11; do not edit.
class Tracebridge < Formula
  desc "Drive Lauterbach TRACE32 PowerView from the command line, VS Code and RustRover"
  homepage "https://github.com/haoyibits/tracebridge"
  version "0.1.11"
  license "MIT"

  bottle do
    root_url "https://github.com/haoyibits/tracebridge/releases/download/v0.1.11"
    sha256 cellar: :any_skip_relocation, arm64_sonoma: "51b2148a41ace705cbce89e06a538a57d7d8405d5ee12ac98f047b628d1923aa"
    sha256 cellar: :any_skip_relocation, sonoma: "fb21c7e0d154acdd6103987b3224fbd3695f8247f9f7ca4ad220ad773ae3c4a4"
    sha256 cellar: :any_skip_relocation, arm64_linux: "1edf4b8d6d8d6a98455602a284c1f3b5fa9694d9f4a5ee18345414e373975ddc"
    sha256 cellar: :any_skip_relocation, x86_64_linux: "3f92d78f1267db930aa4d04d76390cd6deee0755c8170fd790caae38a71a5c97"
  end

  on_macos do
    on_arm do
      url "https://github.com/haoyibits/tracebridge/releases/download/v0.1.11/tracebridge-aarch64-apple-darwin.tar.gz"
      sha256 "eb6b226f9951888d93bd33af416ccfd32235857fc89330d55eeda97016d5a414"
    end
    on_intel do
      url "https://github.com/haoyibits/tracebridge/releases/download/v0.1.11/tracebridge-x86_64-apple-darwin.tar.gz"
      sha256 "d5b556dd2bb226e23ca3483ca500842baba8d25e6fbc260fe2c1ced15704a82d"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/haoyibits/tracebridge/releases/download/v0.1.11/tracebridge-aarch64-unknown-linux-musl.tar.gz"
      sha256 "52b170e1bbe2f0b209bb234e858798310b13acbdff7929f14cdecc71457f6cdd"
    end
    on_intel do
      url "https://github.com/haoyibits/tracebridge/releases/download/v0.1.11/tracebridge-x86_64-unknown-linux-musl.tar.gz"
      sha256 "651607b2592c5c17425b087b1b375b3b784c42ecbdf06f9fde221200999d02cc"
    end
  end

  def install
    bin.install "tracebridge"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/tracebridge --version")
  end
end
