# Generated by packaging/homebrew/formula.sh for tracebridge 0.1.12; do not edit.
class Tracebridge < Formula
  desc "Drive Lauterbach TRACE32 PowerView from the command line, VS Code and RustRover"
  homepage "https://github.com/haoyibits/tracebridge"
  version "0.1.12"
  license "MIT"

  bottle do
    root_url "https://github.com/haoyibits/tracebridge/releases/download/v0.1.12"
    sha256 cellar: :any_skip_relocation, arm64_sonoma: "61e405abab2497c0a052113c0bdb5a279ee7ccaa6c2290ac7e7e864865d17a72"
    sha256 cellar: :any_skip_relocation, sonoma: "b193758083ba1d9d4511fe6d0abde54a913c1181848c7efea9d6234f1c214a27"
    sha256 cellar: :any_skip_relocation, arm64_linux: "3eaf91db2eee8e1db8dc13f88c0589e106ad9cea6580a7893d630a1aa2247e51"
    sha256 cellar: :any_skip_relocation, x86_64_linux: "d20e0b1339c75302fffc086fb218856ecea18f75589a5e6ccab7620150aea6ff"
  end

  on_macos do
    on_arm do
      url "https://github.com/haoyibits/tracebridge/releases/download/v0.1.12/tracebridge-aarch64-apple-darwin.tar.gz"
      sha256 "6a3cc29a0971a4c6ae7d9ad6c57177a19260358e7758588756b849eb0ab73287"
    end
    on_intel do
      url "https://github.com/haoyibits/tracebridge/releases/download/v0.1.12/tracebridge-x86_64-apple-darwin.tar.gz"
      sha256 "fa1ea2e67979eeefcc222f1536e64de88cc38809d1876c2afdcfc9a81d7d0be8"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/haoyibits/tracebridge/releases/download/v0.1.12/tracebridge-aarch64-unknown-linux-musl.tar.gz"
      sha256 "1b17a5b50daedfd21690902c3187ab28fb6051fde18cbac609b76e10c6693ee8"
    end
    on_intel do
      url "https://github.com/haoyibits/tracebridge/releases/download/v0.1.12/tracebridge-x86_64-unknown-linux-musl.tar.gz"
      sha256 "ccfc1ea3a15bdad738c263de664c80f5cfeb469e9ff6b5f866658b75e839d101"
    end
  end

  def install
    bin.install "tracebridge"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/tracebridge --version")
  end
end
