# Generated by packaging/homebrew/formula.sh for tracebridge 0.1.1; do not edit.
class Tracebridge < Formula
  desc "Drive Lauterbach TRACE32 PowerView from the command line, VS Code and RustRover"
  homepage "https://github.com/haoyibits/tracebridge"
  version "0.1.1"
  license "MIT"

  bottle do
    root_url "https://github.com/haoyibits/tracebridge/releases/download/v0.1.1"
    sha256 cellar: :any_skip_relocation, arm64_sonoma: "4f3254598d3aa527b35c1c9e7719e3257a8c47b0018f402b12a88b7822cdd684"
    sha256 cellar: :any_skip_relocation, sonoma: "41ed0489eb5e4c228ab516ce1bbd84e80c3cea41bb84837ecd6ecb8ee186cfc6"
    sha256 cellar: :any_skip_relocation, arm64_linux: "9eecfe421174fd5d98885bf6d0dd2f360cc0c51aa125ec322db0eba993f35f26"
    sha256 cellar: :any_skip_relocation, x86_64_linux: "4a572b84d1071d40fbdfa5381db96c3fba677bb78fcd1f3fe49588d8a9b93aa8"
  end

  on_macos do
    on_arm do
      url "https://github.com/haoyibits/tracebridge/releases/download/v0.1.1/tracebridge-aarch64-apple-darwin.tar.gz"
      sha256 "34154c32a8aa6c0ffc2098d71cd2daf226bf3fac709d0af9c9705e07627341d0"
    end
    on_intel do
      url "https://github.com/haoyibits/tracebridge/releases/download/v0.1.1/tracebridge-x86_64-apple-darwin.tar.gz"
      sha256 "a06f49455dbf56bc9e939c2b048d9cc1c3049f9feaef54c8cf085469d79a2a79"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/haoyibits/tracebridge/releases/download/v0.1.1/tracebridge-aarch64-unknown-linux-musl.tar.gz"
      sha256 "52097655961a567cc9c36e0ab77f4bc84de2ed52749ecacba78ed3657f51dad2"
    end
    on_intel do
      url "https://github.com/haoyibits/tracebridge/releases/download/v0.1.1/tracebridge-x86_64-unknown-linux-musl.tar.gz"
      sha256 "8282ff93f1f2f802320234550c89351e2ca02918bcc0f66954c46da36258d480"
    end
  end

  def install
    bin.install "tracebridge"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/tracebridge --version")
  end
end
